const data = require('./data.json');
const fs = require('fs');
const filtered = data
    .map(item => {
        item.json = JSON.parse(item.json);
        return item;
    })
    .filter(item => item.user.username !== 'test')
    .filter(item => item.user.username !== 'admin')
    .filter(item => item.user.username !== 'straubin')
    .filter(item => item.eventType !== 'RoomUnlockedEvent' || !data.find(i => 
        i.eventType === 'RoomUnlockedEvent' && 
        item.user.username === i.user.username && 
        item.json.roomId === i.json.roomId && 
        item.id > i.id
    ))

fs.writeFileSync('./data.filtered.json', JSON.stringify(filtered, null, 4), 'utf8');

const pretty = filtered
    .map(item => {
        // remove unnecessary user info, flatmap UserComponentKeys
        item.user = item.user.username;
        if (item.json?.userComponentKey) {
            item.json.user = item.json.userComponentKey.user.username;
            item.json.component = item.json.userComponentKey.component.name;
            delete item.json.userComponentKey;
        }

        // remove editable ranges
        if (item.json?.cutSource?.editable) delete item.json.cutSource.editable;
        if (item.json?.testSource?.editable) delete item.json.testSource.editable;
        if (item.json?.autoGeneratedTestSource?.editable) delete item.json.autoGeneratedTestSource.editable;

        // test-executed: wrap test result in object, add component name
        if (item.eventType === 'test-executed') {
            item.json = {
                componentName: item.json.testClassName.replace('Test', ''),
                executionResult: item.json
            };
        }

        // test-/cut-modified: rename component name
        if (item.eventType === 'test-modified' || item.eventType === 'cut-modified') {
            item.json.componentName = item.json.component;
            delete item.json.component;
        }

        // test-execution-failed events do not contain a component name
        if (item.eventType === 'test-execution-failed') {
            const message = item.json;
            const componentName = /.*\n\/(.*?)(Test)?\.java:/.exec(message)[1];
            item.json = {componentName, message};
        }

        // rename json to data
        item.data = item.json;
        delete item.json;

        return item;
    });

fs.writeFileSync('./data.pretty.json', JSON.stringify(pretty, null, 4), 'utf8');

const eventTypes = pretty
    .map(item => item.eventType)
    .filter((value, index, self) => self.indexOf(value) === index);

fs.writeFileSync('./eventTypes.json', JSON.stringify(eventTypes, null, 4), 'utf8');

const usernames = pretty
    .map(item => item.user)
    .filter((value, index, self) => self.indexOf(value) === index);

fs.writeFileSync('./usernames.json', JSON.stringify(usernames, null, 4), 'utf8');
